steps:
- name: Build & publish
  image: woodpeckerci/plugin-docker-buildx:6
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: ghcr.io
    repo: ghcr.io/dhandspikerwade/ups-taint
    tags:
      - latest
      - 1
      - ${CI_COMMIT_TAG}
    default_labels: false
    dry_run: false
    platforms: linux/amd64
  when:
    branch:
    - main
    event: [ tag ]

- name: Build Image
  image: woodpeckerci/plugin-docker-buildx:6
  settings:
    registry: ghcr.io
    repo: ghcr.io/dhandspikerwade/ups-taint
    tags:
      - latest
    default_labels: false
    dry_run: true
    platforms: linux/amd64
  when:
    branch:
      exclude: [ main ]
    event: [ push, manual ]